#!/bin/bash
echo "PARCEL_DIRNAME: ${PARCEL_DIRNAME}"
ELASTICSEARCH_DIRNAME=${PARCEL_DIRNAME:-"ELASTICSEARCH"}
echo "ELASTICSEARCH_DIRNAME: ${ELASTICSEARCH_DIRNAME}"
ELASTICSEARCH_HOME=${PARCELS_ROOT}/${ELASTICSEARCH_DIRNAME}
echo "ELASTICSEARCH_HOME: ${ELASTICSEARCH_HOME}"
export ELASTICSEARCH_HOME
